### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by alexhallam**
Isn't docker and aws cli needed?

### CODE REVIEW

**Review by larsll — CHANGES_REQUESTED** [review]
Please move the additions to the Installation heading.

**Comment by alexhallam** [comment]
After looking at the install script. I think the install script downloads docker.

**Comment by larsll** [comment]
The correct place would be after this comment:

> For local install it is recommended not to run the bin/prepare.sh script; it might do more changes than what you want. Rather ensure that all prerequisites are set up and run bin/init.sh directly.

The issue is that the list of requirements is not really listed (packages, etc.); hence it would be the right place to amend.

**Comment by larsll** [comment]
No activity. Closing.

**Pull request closed without merging**
