### PR TITLE
add additional robo env vars

### PR DESCRIPTION
**Pull request by MarkRoss-Eviden**
Provides additional vars into the container which can be used to understand what training is happening.

### CODE REVIEW

**Comment by larsll** [comment]
Are these required? The values are passed into the simulator through https://github.com/aws-deepracer-community/deepracer-for-cloud/blob/6d7b71d14d82e0eedadb0422fa685096fa7fc9fa/scripts/training/prepare-config.py#L45

**Comment by MarkRoss-Eviden** [comment]
as far as I'm aware though Robomaker isn't aware of those vars (at least i didn't find them in my testing before i submitted the PR), so if you want to be aware of what direction you're racing in the Robomaker container needs them just like world name is passed in?

**Comment by larsll** [comment]
It is not a variable, it is in the training_params.yaml that gets created and uploaded.

**Comment by MarkRoss-Eviden** [comment]
if you do a 'print(str(os.environ))' in your reward function it's not aware of direction (reverse or not), but it is aware of track name.  Is there an alternative way of it knowing I'm not aware of that is already available and I just need a different way to reference it??

**Comment by larsll** [comment]
`reversed = params["is_reversed"]`

**Comment by MarkRoss-Eviden** [comment]
doesn't that define whether the car is going in the 'wrong' direction rather than whether the entire world has been reversed?

**Comment by larsll** [comment]
Tested -- is_reversed actually is giving the direction that REVERSE_DIR or ALTERNATE_DRIVING_DIRECTION is dictating, not if the car is spinning around. It could of course be that this is superimposed; that if you start off with is_reversed=True, then it gets =False when the car drives in the wrong direction.

**Pull request closed without merging**
